server:
  port: ${port:9283}

spring:
  application:
    name: provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.22.126:8848
logging:
  level:
    root: info
    org.springframework: info