server:
  port: 9284

spring:
  application:
    name: consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.22.126:8848
logging:
  level:
    root: info
    org.springframework: info